### ISSUE TITLE
Deploy to maven.scijava.org

### ISSUE THREAD

**Issue by imagejan** [trackmate-sc/TrackMate-CTCRunner#5]
The page https://imagej.net/plugins/trackmate/extensions/trackmate-helper is currently pointing to the wrong source code on GitHub, because the artifact is set as `sc.fiji:TrackMate` where it should be `sc.fiji:TrackMate-CTCRunner`. But the maven artifact of this repository here is not deployed.

I suggest:
* adding CI via GitHub actions (i.e. running `github-actionify.sh` from `scijava-scripts`
* transferring this repo to the `fiji` organization (or asking @ctrueden to add the maven secrets just for this repo in your personal space @tinevez)
* fixing the artifact name on the wiki page.

That would have made it much easier for me to find the source code when troubleshooting for users of our core facility 🙂.

**Comment by tinevez** [comment]
We should do this for all TrackMate-* stuff I maintain.

**Comment by imagejan** [comment]
@tinevez do you want to move all to the `fiji` org? Or do you prefer an own organization such as `trackmate`? In any case, I'll be happy to run the `github-actionify.sh` and submit pull requests for all repos, once they are in their final location.

**Comment by tinevez** [comment]
Hello @imagejan 
We started a discussion on zulip on this very topic:
https://imagesc.zulipchat.com/#narrow/stream/327238-Fiji/topic/Move.20tinevez.20TrackMate.20extensions.20to.20Fiji.3F

As you can see it reached a bit beyond but we have a plan that will implement your suggestions.

**Comment by ctrueden** [comment]
An update on this issue: since the above discussion, we migrated TrackMate and its extensions to a dedicated `trackmate-sc` org. I thought the components were all set up with GitHub Actions, but taking a look again now, I saw that the configuration were outdated and/or wrong, so I have now fixed them all to have a single identical `/.github/workflows/build.yml` according to current best practices.

Some of the components have already deployed snapshots to maven.scijava.org automatically, but others have dependency issues. This component (TrackMate-CTCRunner) in particular depends on most of the others, so it has not yet deployed successfully due to these issues:

> The following artifacts could not be resolved: sc.fiji:TrackMate-StarDist:jar:1.1.2, sc.fiji:TrackMate-MorphoLibJ:jar:1.1.0, sc.fiji:TrackMate-Cellpose:jar:0.0.5, sc.fiji:TrackMate-Ilastik:jar:1.1.0, sc.fiji:TrackMate-Weka:jar:1.1.0, net.celltrackingchallenge:CTC-measures:jar:0.9.0

And digging down into those builds:

### TrackMate-StarDist

Missing dependency:

> Could not resolve dependencies for project sc.fiji:TrackMate-StarDist:jar:1.1.3: Could not find artifact de.csbdresden:StarDist_:jar:0.3.0

Solution: get `de.csbdresden:StarDist_` deployed to maven.scijava.org. See trackmate-sc/TrackMate-StarDist#5.

### TrackMate-MorphLibJ

Build was passing, but no release had been done with the current infrastructure. [Released version 1.1.2](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-MorphoLibJ~1.1.2~~).

### TrackMate-Cellpose

Build was passing, but no release had been done with the current infrastructure. [Released TrackMate-Cellpose 0.0.7](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-Cellpose~0.0.7~~).

### TrackMate-Ilastik

Was using unreleased TrackMate features. [Released TrackMate 7.9.0](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate~7.9.0~~). Then [released TrackMate-Ilastik 1.2.2](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-Ilastik~1.2.2~~).

### TrackMate-Weka

Build was passing, but no release had been done with the current infrastructure. [Released TrackMate-Weka 1.1.1](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-Weka~1.1.1~~).

### Remaining issues

The following components need a release deployed to maven.scijava.org before TrackMate-CTCRunner can be released and deployed:

* `net.celltrackingchallenge:CTC-measures`
* `sc.fiji:TrackMate-StarDist` (trackmate-sc/TrackMate-StarDist#5)
    * `de.csbdresden:StarDist_`

### Other TrackMate component releases

Even though they are not dependencies of TrackMate-CTCRunner, I also made initial releases of the other TrackMate extensions:

* [TrackMate-CSVImporter 3.1.2](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-CSVImporter~3.1.2~~)
* [TrackMate-ExTrack 1.2.4](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-ExTrack~1.2.4~~)
* [TrackMate-Oneat 3.0.0](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-Oneat~3.0.0~~) (build was failing due to a javac compilation error, but I fixed it)
* [TrackMate-Skeleton 2.0.0](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-Skeleton~2.0.0~~)

### Component management in the BOM

All components released thus far have been added to pom-scijava version management (scijava/pom-scijava@9ec5bc2380334e1d9ce9bb479b0141e2fecd8363). We can add the rest once the above issues have been resolved and the remaining components have been released.

**Comment by tinevez** [comment]
Update:

This still fails because the build fails on the CI for every changes we make.
The reason for the CI build to fail is that it cannot find the CTC measures artifact on the maven repo.
I will write to Vlado about this.

**Comment by ctrueden** [comment]
@tinevez In the meantime, if you are impatient, we could hack the CI in this repository to also build and deploy the CTC measures artifact first. :smiling_imp:

**Comment by ctrueden** [comment]
On second thought... I just checked out the existing release tags/branches from the measures repo, and deployed them to maven.scijava.org myself. So @tinevez we can now depend on 0.9.6, 0.9.7, 1.0.0, or 1.0.1. I have now updated this repository to depend on 1.0.1. The build passes locally for me; we'll see how CI does!

**Comment by ctrueden** [comment]
[Build passed](https://github.com/trackmate-sc/TrackMate-CTCRunner/actions/runs/5465605397), and TrackMate-CTCRunner artifact is [now deployed](https://maven.scijava.org/#nexus-search;gav~sc.fiji~TrackMate-CTCRunner~~~). :smile:

**Comment by xulman** [comment]
sorry @ctrueden and @tinevez for the CTC measures mess (and for my silence recently)

I will work with Curtis to publish (the current and future versions of) the measures to scijava.maven
